version: '3.8'

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loan_default
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mlops-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - '5000:5000'
    command: mlflow server --host 0.0.0.0 --port 5000
    volumes:
      - ./mlruns:/mlruns
    networks:
      - mlops-network

  airflow:
    image: apache/airflow:2.8.0
    environment:
      AIRFLOW_CORE_EXECUTOR: LocalExecutor
      AIRFLOW_DATABASE_SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:password@postgres/loan_default
      AIRFLOW_CORE_LOAD_EXAMPLES: 'false'
    ports:
      - '8080:8080'
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres
    command: standalone
    networks:
      - mlops-network

volumes:
  pgdata:

networks:
  mlops-network:
    driver: bridge